### PR TITLE
Added dept. tags

### PR DESCRIPTION
**Pull request by pandaxtc**
**What you added/changed:**
Added Bulma tags to each character title that specifies their department and title

**Why you did this:**
@Xetera said we should add them in https://github.com/Xetera/hifumi.io/issues/33

**Is this currently good enough to merge?**
Yes, pending review

### CODE REVIEW

**Comment by itsaferbie** [comment]
Personally, the white text on the light purple is a bit hard to read at the size it is. Maybe change text to be a gray or darken the purple slightly.

**Comment by Xetera** [comment]
this is a tiny bit problematic

**Comment by jvyden420** [comment]
well sometimes they write vertically in japan so this is fine /s

**Comment by Xetera** [comment]
please open a new pull request with the gatsby rework instead

**Pull request closed without merging**
